import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';

const notoSans = Noto_Sans({ subsets: ['latin'], weight: ['400', '600'] });

export const metadata: Metadata = {
  title: 'Expeditions App',
  description: 'Generated by create next app',
  openGraph: {
    siteName: 'Expeditions',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={notoSans.className}>
        <nav>This is nav</nav>
        {children}
        <footer>This is footer</footer>
      </body>
    </html>
  );
}
